### ISSUE TITLE
Feature request Add Present to Spawn 

### ISSUE THREAD

**Issue by Aipoc76** [macroquest/macroquest#559]
Requesting the member "Present" be added to spawn, to identify if said spawn is online and in same zone. 
This would only work for PC's obviously.

It would act the exact same way as Group.Member.Present but be more robust.

**Comment by dannuic** [comment]
Spawn information is only available in the current zone. There is no need for this member because if you have spawn information, the spawn is in the zone.

**Comment by brainiac** [comment]
how would this be used? a spawn is always present (you can't have spawns that aren't in the zone)

**Comment by Aipoc76** [comment]
so using ${Spawn[pc soandso].ID} is effectively doing the same thing?  If this is true, please close.

**Comment by brainiac** [comment]
${Spawn} will only return things that exist in the zone.
