### ISSUE TITLE
Spell[ ].MyRange appears to just read the normal .Range

### ISSUE THREAD

**Issue by Aipoc76** [macroquest/macroquest#563]
Not getting proper return on MyRange.  It's only returning the normal unmodified range.

Steps to reproduce, /echo ${Spell[AnySpellHere].MyRange}

I used the macroquest expression evaluator also.

![image](https://user-images.githubusercontent.com/42475106/168321119-b7d6ae01-2b5b-47ce-96db-edee527e5375.png)

**Comment by nytemyst** [comment]
I can also reproduce this using a number of spells. These are 

Terror of Narus
Impose for power

Focus being used is called Reach of Wenteras which increases the range of detrimental spells by 35%

MyDuration is also affected. Spell being used. Staunch Stance. Focus Effect Gift of the Timeless. Increases duration by 35% for beneficial spells

and also MyCastTime. Spell being used also Staunch Stance. Focus effect Gift of the Ashen. Reduce cast time of beneficial spells by 30%

**Comment by Aipoc76** [comment]
Did some more testing, With Wild Growth, It appears that the Range is actually working as intended.  It's the Echo / display in evaluator that is wrong.  As you can tell from the pic the spell is actually casting at 126.65, If i go past 127 it does not cast.  The Evaluator / Echos are showing the same values of 100, and not the Correct value for MyRange of 127.
![image](https://user-images.githubusercontent.com/42475106/170805843-4e77883f-fb0b-4cee-8a5a-5eeffae8a254.png)

MyDuration is working as intended.

![image](https://user-images.githubusercontent.com/42475106/170806095-bad33841-66eb-4ac2-8b9f-bc7ed1407584.png)

**Comment by exspes007** [comment]
can i bump this. has a fairly significant impact on healing.

**Comment by Sicprofundus** [comment]
using a debug build i get what is expected

```less
> /echo ${Spell[salve of clorith].MyRange}
254.00
```

![image](https://user-images.githubusercontent.com/48923666/180451346-31e96a8b-5033-4c2b-b2c1-a0eb8184872a.png)

but using release build i don't
![image](https://user-images.githubusercontent.com/48923666/180451265-27b68aed-d83f-44b4-ac4f-edca53def7e9.png)

**Comment by Knightly1** [comment]
This issue is actually one of optimization, which is partly why it was fixed in debug but not in release.   To resolve it we're going to move all of the FUNCTION_AT_ADDRESS blocks inot their own cpp file.  I'd call it a reorganization, but it's actually a deorganization.
