### ISSUE TITLE
Feature Request - Add Status to AdvLoot TLO Datatype

### ISSUE THREAD

**Issue by nytemyst** [macroquest/macroquest#565]
Don't know if it's possible but being able to see the current autoroll status on the SList.Right now there's a AutoRoll datatype that just returns bool.  Would like another datatype called Status that would say whether a roll is currently happening or a roll has already finished.

And icon does show up when an autoroll begins and when it ends so i'm happy we're getting that data.

**Comment by brainiac** [comment]
This was implemented in 10fa9fbd110dd4dd6f5d92f63e561323e116b6ca
