### ISSUE TITLE
[emu] CTD on ImGui Demo

### ISSUE THREAD

**Issue by johnfking** [macroquest/macroquest#585]
Dear ImGui Demo => Configuration => (click) io.ConfigFlags: ViewportsEnable = CTD

**Comment by brainiac** [comment]
Is this emu specific? I didn't even know this option in the demo existed but i wouldn't expect it to work. Enabling viewports should only be done through the mq settings window.

**Comment by johnfking** [comment]
I have not checked this against the live build, so unsure if it's emu-specific.

**Comment by brainiac** [comment]
I don't expec tthe ViewportsEnable checkbox to work, and I also don't want to make any changes to the demo code, so closing this as a won't fix.
