### ISSUE TITLE
[emu] Attemtping to itemnotify item in closed bag seems to do nothing

### ISSUE THREAD

**Issue by projecteon** [macroquest/macroquest#592]
Attempting to pick up 1 item from a stack inside bag 1 slot 2.

`/ctrl /itemnotify in pack1 2 leftmouseup`

Gives no error and cursor remains empty.
This worked in MQ2.

**Comment by brainiac** [comment]
Had an issue with the offset for the multiple item move function, but fixing it reveals that the server doesn't support this method of moving items. This will require additional work.
