### ISSUE TITLE
Guild names not displaying properly

### ISSUE THREAD

**Issue by johnfking** [macroquest/macroquest#594]
![image](https://user-images.githubusercontent.com/414568/181935310-a235dc13-4318-4755-af19-62348357e005.png)

Latest build as 7/30/2020

No extra plugins; just default build

**Comment by brainiac** [comment]
What is the guild name supposed to be? Is this yourself or another player? what happens if you /echo the values?

**Comment by Sicprofundus** [comment]
Assuming emu?, gonna tag it

Can you confirm @johnfking

**Comment by johnfking** [comment]
Emu build.  The guild name should be "Snakebite"  The in-game display is correct (The Guild Management Window).  Echo'ing values from either Lua or Macro Expression Eval result in nil (and NULL)

**Comment by dannuic** [comment]
This is fixed in eqlib https://github.com/macroquest/eqlib/commit/847d125525aed85428fbac6e710495ea85f93f44
