### ISSUE TITLE
CastRadius/SpellRadius do not save values.

### ISSUE THREAD

**Issue by FelisMalum** [macroquest/macroquest#600]
When using "/mapfilter castradius x" or spellradius the circles are correctly drawn on the map but are saved to the ini as =1. Seems to be saved as a bool and not an init. All settings of >0 result in a =1 in the ini. No circles appear on the map upon re-long. Can only assume there being drawn w a radius=1. Manually editing the ini still gets changed back to a =1

**Comment by Knightly1** [comment]
This was resolved in 688354f5d7bd9
