### ISSUE TITLE
/follow vs /afollow

### ISSUE THREAD

**Issue by kaen01** [macroquest/macroquest#604]
The plugin MQ2advpath has for as long as i am aware mapped the EQ command /follow to its /afollow command.

/afollow is very intrusive as it does not break from following and follows in a non eq manner, this often seems to confuse current mq users and newer mq users.

would there be a case for separating the two commands? /follow works as eq wants it to, and /afollow works as the mq plugin wants it to.

**Comment by Knightly1** [comment]
Posted this issue to the mq2advpath repo: https://gitlab.com/redguides/plugins/mq2advpath/-/issues/1

**Comment by FelisMalum** [comment]
I second the notion, it can be quite annoying when all you want is a simple follow and get the more advanced one.
