### ISSUE TITLE
EQBC server needs to run in realtime or high process priority or it lags

### ISSUE THREAD

**Issue by ew6082** [macroquest/macroquest#610]
This is probably not a high priority issue, but EQBC server runs a bit slower than a 300 baud modem when the machine gets loaded up unless you set the process priority to realtime or high.   I usually do this manually, but i think this could probably be automatically set by starting the server process with the /high or /realtime flags?  

I'd do a .bat file but now we're changing the process name every patch so it's not particularly convenient.  Not sure how hard this is to implement since it seems like it needs admin permission to do this based on my limited research.

**Comment by Knightly1** [comment]
EQBC isn't part of MQ's code base.  I've posed the issue here: https://gitlab.com/redguides/plugins/mq2eqbc/-/issues/3
