### ISSUE TITLE
[emu] KissAssist/MuleAssist crash when buffing targets

### ISSUE THREAD

**Issue by mcbaine2** [macroquest/macroquest#614]
When running through buffing routine and the character attempts to buff any target other than themselves, the client immediately crashes with unrecoverable error. Able to resolve on my cleric by setting |me flag on all group buffs and removing single target buffs from ini.
Debug attachment shows this as the last entry but I'm too smooth brained to understand it
MQ2Main!mq::SpawnBuffs::Get::__l2::<lambda_bc721fd30d9338a985873be68719e011>::operator()+0x3 [inlined in MQ2Main!mq::SpawnBuffs::Get+0x23]

Buff Section to cause crash
[Buffs]
BuffsOn=2
BuffsSize=10
Buffs1=Hand of Virtue
Buffs2=Kazad's Mark|MA
Buffs3=Spirit Mastery|dual|Aura of Pious Divinity Effect|Aura
Buffs4=Aura of Reverence|me
Buffs5=Armor of the Zealot|me
Buffs6=Maelin's Methodical Mind|me
Buffs7=Form of Rejuvenation II|me
Buffs8=command:/sit|cond3
Buffs9=Shawl of Eternal Forces|dual|Maelin's Methodical Mind
Buffs10=Belt of Tidal Energy|dual|Form of Rejuvenation
RebuffOn=1
CheckBuffsTimer=10

**Comment by brainiac** [comment]
@mcbaine2 can you try this again with latest emu code? I wasn't able to reproduce the issue with the information you provided, but i did fix other issues so i'm hoping its something else that i fixed already.

**Comment by brainiac** [comment]
closing due to lack of response
