### ISSUE TITLE
Lua parsing issue with floats on Live

### ISSUE THREAD

**Issue by hytiek** [macroquest/macroquest#615]
```
> /lua parse 900*1.1
989.99999999999
> /lua parse string.format("%f", 900*1.1)
989.999999
> /lua parse string.format("%0.0f", 900*1.1)
989
> /lua parse tonumber(string.format("%0.0f", 900*1.1))
989
```

while this works properly on emu.

Relates to: https://github.com/macroquest/macroquest/issues/351

**Comment by dannuic** [comment]
These are all equivalent values to floats, this isn't an error

**Comment by dannuic** [comment]
Check out [IEEE-754](https://en.wikipedia.org/wiki/IEEE_754)

**Comment by brainiac** [comment]
its because of the rounding mode set by eq in live client.

**Comment by hytiek** [comment]
I assume you asked me to open this to have tracking for others.
