### ISSUE TITLE
CharSelectList Causes Client Crash

### ISSUE THREAD

**Issue by johnfking** [macroquest/macroquest#627]
At the login screen

`mq.TLO.EverQuest.GameState()` = CHARSELECT

`mq.TLO.EverQuest.CharSelectList()` = nil
`mq.TLO.EverQuest.CharSelectList(1).Count()` = 1601793132
`mq.TLO.EverQuest.CharSelectList(2).Count()` = 1601703132

`mq.TLO.EverQuest.CharSelectList(1).Name()` = CTD

**Comment by johnfking** [comment]
Yes

**Comment by brainiac** [comment]
Fixed via https://github.com/macroquest/eqlib/commit/fb0f1cf740be048b2c2d1116db062f57aa3d4636

**Comment by brainiac** [comment]
Checked and live is working fine so this is just emu.
