### ISSUE TITLE
[emu] MQ2ChatWnd does not save window settings

### ISSUE THREAD

**Issue by SirCabby** [macroquest/macroquest#628]
We recently got a fix to allow for changing settings on the MQ2ChatWnd via the right click context popup, however none of these settings are saved on log, and everything reverts back.  Looking for a fix to save changes, as well as window position.

**Comment by brainiac** [comment]
@SirCabby not sure I understand what the issue is. can you provide specifics? Settings seem to save for me.

**Comment by SirCabby** [comment]
> @SirCabby not sure I understand what the issue is. can you provide specifics? Settings seem to save for me.

I'll try to reproduce now and let you know

**Comment by SirCabby** [comment]
> @SirCabby not sure I understand what the issue is. can you provide specifics? Settings seem to save for me.

Cannot reproduce.  Seems to be working.
