### ISSUE TITLE
Running EQ + MQ Emu disables some keys on Swedish keyboard (mainly backtick and tilde)

### ISSUE THREAD

**Issue by Mazena86** [macroquest/macroquest#652]
I'm running the latest MQ for emulated servers installed through RG launcher. When EQ is running with MQ, I cannot type ~ or ` anymore. Tilde especially is a bit annoying since it's used in Lua scripting. On my keyboard to type a tilde, I need to use ALT+^, and to type a backtick, I need to use Shift+´.

Someone suggested checking out if MacroQuest.ini would be using these keys and replacing them. The only one I noticed was ToggleConsoleKey using CTRL +  ´, but changing the key binding or removing the line altogether did not help with the issue.

**Comment by Mazena86** [comment]
You're right. I opened only EverQuest now and the same issue is still present. I guess it's an issue with EQ and not MQ. I'll go ahead and close the issue then.

**Comment by martinlindhe** [comment]
Besides ~, I cannot enter the ^ symbol in game either with Swedish keyboard.

**Comment by kaldo989** [comment]
Try Ctrl+ö for console
