### ISSUE TITLE
ImGui Critical Failure specificity

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#654]
When using a listboxheader, if you don't have the listbox footer, you get an imgui crash, as expected - but the error message provided is "ImGui Critical Failure: Must call EndChild() and not End()!". I'm not sure if this is something worth issue/bugging or if it is something that is possible to improve on the warning/error messages to be more specific.

here is a snippet with the ListBoxFooter commented out, which would result in the aforementioned error message and not a "Must have a ListBoxFooter() to close the ListBoxHeader()

```cpp
ImGui::BeginChild("##cool", ImVec2(0, -ImGui::GetFrameHeightWithSpacing() - 4), false);

ImGui::Text("Cool List");
{
    if (ImGui::ListBoxHeader("##CoolList", ImGui::GetWindowSize().x, ImGui::GetWindowSize().y)) {
        ImGui::Text("Cool Text");
    }

    //ImGui::ListBoxFooter();
}
ImGui::EndChild();

**Comment by brainiac** [comment]
Error comes from imgui library. ListBoxHeader calls BeginChild, and ListBoxFooter calls EndChild.

What happens is the ImGui::EndChild that you wrote, closes the listbox, and then it reaches the End() that you have on your window, triggering the error.

The error is technically accurate, however it is not something within our control to improve.
