### ISSUE TITLE
Raid.Level and Raid.Class have wrong values, maybe raid TLO in general

### ISSUE THREAD

**Issue by aquietone** [macroquest/macroquest#685]
on a lvl 70 warrior on project lazarus where raid member 1 is the toon running the commands, which has the standard set of eq classes.
```
> /echo ${Raid.Member[1].Level}
326
> /echo ${Raid.Member[1].Class}
UNKNOWN CLASS
```

**Comment by brainiac** [comment]
Need to verify raid support. linked to #643
