### ISSUE TITLE
EMU ParseItemLink returns false

### ISSUE THREAD

**Issue by aquietone** [macroquest/macroquest#689]
It seems like `ParseItemLink` on EMU is returning false incorrectly, causing MQ2LinkDB not to work on EMU. Rekka made it work in his build by changing all the checks on ParseItemLink return value to just check if linkData.itemID > 0 and it appears to work (or at least not break, and valid links are returned). So, even though ParseItemLink is returning false, it seems to be getting far enough in the parsing that its doing something useful?

For example, the changes were like:
```
@@ -311,9 +311,13 @@ void CreateIndex()
 static bool FindLink(std::string_view link)
 {
        ItemLinkInfo findLink;
-       if (!ParseItemLink(link, findLink))
-               return false;
+       ParseItemLink(link, findLink);

+       if (findLink.itemID == 0)
+       {
+               return false;
+       }
```

**Comment by brainiac** [comment]
full item links support is still a todo on #643
