### ISSUE TITLE
Every PC in Group Returns True as MasterLooter

### ISSUE THREAD

**Issue by cannonballdex** [macroquest/macroquest#690]
`mq.TLO.Group.MasterLooter()`
`mq.TLO.Group.Member(1).MasterLooter()`

**Comment by dannuic** [comment]
Your first code example there returns the master looter of the group, which is a type that lua doesn't understand. So when you do () on it, you're just going to get a string of the local player's name (which seems wrong, but is not this bug).

**Comment by Knightly1** [comment]
It's not a boolean.

**Comment by dannuic** [comment]
it's a boolean on the member datatype, but I cannot repro this. Can you provide repro steps?

`> /lua parse mq.TLO.Group.Member(1).MasterLooter()
true
> /lua parse mq.TLO.Group.Member(2).MasterLooter()
nil
`

**Comment by cannonballdex** [comment]
Ok I was looking for 'mq.TLO.Group.MasterLooter()' to return the MasterLooter.
