### ISSUE TITLE
[BUG] Hiding IMGUI Overlay causes mouse cursor to not affect EQ UI

### ISSUE THREAD

**Issue by amosssnake00** [macroquest/macroquest#699]
Hiding the IMGUI Overlay with an assigned key combination (TOGGLE_IMGUI_OVERLAY) while the cursor is in an IMGUI window (tested: boxhud, LEM, buttonmaster - but also plain MQ console when not in focus) causes mouse cursor to lose touch with EQ interface (cannot click anything, no mouse over effects).

Settings: 
- Start with MQ Console enabled
- Use Autologin
- Hotkey for toggle MQ console / Toggle IMGUI Overlay set

1. MQ console is visible & active
2. click any EQ UI element so MQ console loses focus, 
3. hover mouse over MQ console area
5. press TOGGLE_IMGUI_OVERLAY key
6. IMGUI is gone
7. cursor cannot click anything in EQ
8. press TOGGLE_IMGUI_OVERLAY key
9. EQ UI clickable again (might need re-clicking of mouse)
11. move mouse outside all IMGUI windows areas
12. press TOGGLE_IMGUI_OVERLAY key
13. EQ UI still clickable

(this works with all IMGUI windows)

**MQ Version**
- [X] Live
- [x] Test
- [x] Emu (ROF2)

**Comment by GhostD2R** [comment]
Confirmed the same behavior following his example.
