### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LamahHerder** [macroquest/macroquest#707]
**Describe the bug**
haSheD.exe shows in taskmanager background process's if mq is run from a network share, however it is not shown if run locally

**To Reproduce**
1 - run macroquest.exe from c:\macroquest\macroquest
2 - view taskmanager (no hashed.exe in background process)
3 - run macroquest.exe from a \\network\macroquest\macroquest.exe
4 - view taskmanager, notice hashed exe in background process

**Expected behavior**
hashed.exe of macroquest.exe should not show in background process's in taskmanager

**Screenshots**
![image](https://user-images.githubusercontent.com/22425296/227747130-47a05fde-eb73-47a7-96b3-a3e68c553b91.png)

**MQ Version**
- [ x ] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**

**Comment by brainiac** [comment]
I’m sorry, even with you explanation I don’t understand what the bug is.

**Comment by LamahHerder** [comment]
> I’m sorry, even with your explanation I don’t understand what the bug is. How does task manager affect its behavior?

Assuming if its not hiding the process if executed from network whatever anti-detection things may not be functioning, while I understand DBG can/will do whatever they want the security blanket is preferable

**Comment by brainiac** [comment]
The process is not hidden from task manager
