### ISSUE TITLE
[BUG] pEverQuestInfo->bAutoAttack on Test incorrect information.

### ISSUE THREAD

**Issue by jessebevil** [macroquest/macroquest#712]
**Describe the bug**
pEverQuestInfo->bAutoAttack reports incorrect information when output or checked compared to current live build on test. 

**To Reproduce**
1. Turn on attack
2. Echo ${Me.Combat}

**Expected behavior**
When attack is on, the bool should return true. However, it returns false. 

**MQ Version**
- [X] Test

**Additional context**
We're aware the issue may already be something you're tracking, but users lead me to the issue as it related to the plugins and lead me and Sic directly to the problematic code on our side and a few simple tests were able to track it down fairly quickly. Just in case you were not already tracking this we wanted to create an issue so you wouldn't have to hunt down the information.

**Comment by brainiac** [comment]
thanks for the report
