### ISSUE TITLE
[BUG] ${Me.GroupAssistTarget} and Spawn[].TargetOfTarget always NULL

### ISSUE THREAD

**Issue by LamahHerder** [macroquest/macroquest#713]
**Describe the bug**
${Me.GroupAssistTarget} always returns NULL
DOC's say character data has .GroupAssistTarget

**To Reproduce**
1. Make a group
2. Set someone as groupassist
3. /echo ${Me.GroupAssistTarget} (its NULL)
4. confirm in UI group assist has a target
5. confirm a group assist exists ${Me.MainAssist}
6.  set xtarget /xt set 5 groupassisttarget
7. confirm xtarget window shows with proper groupassisttarget spawn
8. try /echo ${Me.GroupAssistTarget} again (its NULL)

**Expected behavior**
GroupAssistTarget gives you a spawn

**Screenshots**

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**

Did notice that ${Me.RaidAssistTarget[#]} works if you set it properly in a raid

**Comment by Voidless22** [comment]
Have you double checked it's spelled correctly? If you open your MQ Console and click the Tools Menu, you can use the Macro Expression Evaluator to verify. It is working for me on the current RG Live build
![image](https://user-images.githubusercontent.com/79501102/230746395-fd85a469-9131-4113-8679-38198b900f9b.png)

**Comment by LamahHerder** [comment]
![image](https://user-images.githubusercontent.com/22425296/230750422-00ebcfc2-1005-48f0-9a8b-87264005c33b.png)

**Comment by LamahHerder** [comment]
Aaaaandddd... restarting PC and now its working... sigh
![image](https://user-images.githubusercontent.com/22425296/230750512-d2e56682-b543-4eca-9291-c120e51d016f.png)
