### ISSUE TITLE
Macro - :OnExit skips the first line when /endmac is called from within the macro

### ISSUE THREAD

**Issue by Knightly1** [macroquest/macroquest#726]
**To Reproduce**
```
Sub Main()
    /echo Begin testing issue
    /endmac
    /echo Test Failed
:OnExit
    /echo First line
    /echo End testing issue
/return
```

Output is:
```
Begin testing issue
End testing issue
```

**Expected behavior**
Output should be:
```
Begin testing issue
First line
End testing issue
```

**MQ Version**
- [X] Live
- [X] Test
- [X] Emu (ROF2)

**Additional context**
This issue is heavily related to issue #703

**Comment by Knightly1** [comment]
Note that resolution on this issue needs to be tested under the following conditions and all should have the same behavior

[ ] /endmac is called from the console
[ ] /endmac is called from the main sub
[ ] /endmac is called from a separate sub
[ ] /endmac is called from an inc file

**Comment by bytebite01** [comment]
Added a last test5 for a sub calling second sub and clearing both First sub and Main from stack.

`-- test1.mac console /endmacro use
Sub Main()
    /echo Entering forever loop.  /endmacro to end
	/while (1) {
		/delay 1s
		/echo 1 second has passed.
	}
    /echo Test Failed
:OnExit
	/echo In :OnExit, calling Main Exit.
	/call MainExit
/return

Sub MainExit
	/echo In MainExit
/return`

`-- test2.mac  /endmac from main sub
Sub Main()
    /echo Testing mac2
	/endmacro
	/echo You Failed.
:OnExit
	/echo Calling MainExit
	/call MainExit
/return

Sub MainExit
   /echo In MainExit
/return`

`-- test3.mac /endmac from separate sub
Sub Main()
    /echo Testing test3
	/call testEnd
	/echo FAILURE!
:OnExit
	/call MainExit
/return

Sub testEnd()
    /echo Testing endmac
	/endmac
	/echo FAILURE!
/return

Sub MainExit
   /echo In MainExit
/return`

-- test4.mac  end mac from include
#include test4.inc
Sub Main()
	/echo Testing test4
    /call testEnd
    /echo Test Failed
:OnExit
   /call MainExit
/return

Sub MainExit
   /echo In MainExit
/return`

`-- test4.inc  endmac from inc
Sub testEnd()
    /echo Testing endmac included
    /endmac
/return`

`-- test5.mac /endmac from separate sub * 2
Sub Main()
    /echo Testing test5
	/call testEnd1
	/echo FAILURE!
:OnExit
	/call MainExit
/return

Sub testEnd1()
    /echo Testing endmac1
	/call testEnd2
	/echo FAILURE!
/return

Sub testEnd2()
    /echo Testing endmac2
	/endmac
	/echo FAILURE!
/return

Sub MainExit
   /echo In MainExit
/return`

**Comment by bytebite01** [comment]
It fails test6 in that the local scope changes from the Sub to Main.   Here is test6:  

```
-- test6.mac /endmac from separate sub and check scope of variables
Sub Main()
    /echo Testing test6
	/declare mainOuter	int	outer 1
	/declare mainLocal	int local 2
	/call testEnd1
	/echo FAILURE!
:OnExit
	/echo Skip this line cause of #726 bug.
	/call MainExit
	
	/if (${Defined[mainOuter]}) {
		/echo mainOuter is ${mainOuter}
	}
	/if (${Defined[mainLocal]}) {
		/echo mainLocal is ${mainLocal}
	}
	/if (${Defined[subOuter]}) {
		/echo subOuter is ${subOuter}
	}
	/if (${Defined[subLocal]}) {
		/echo subLocal is ${subLocal}
	}
	/endmac
/return

Sub testEnd1()
    /echo Testing endmac1
	/declare subOuter	int	outer 3
	/declare subLocal	int local 4
	/endmac
	/echo FAILURE!
/return

Sub MainExit
   /echo In MainExit
/return
```

**Comment by Knightly1** [comment]
Good test on Test 6.

Overall, this is a question of what the correct output is more than the difference in your outputs.  I believe your original PR behavior to be correct (versus the original code behavior which you've matched).  An outer variable is available to the whole macro.  A local variable is available to the sub (and not the sub of a sub).

Therefore, the original behavior of that output is in question:
```
mainOuter is 1
subOuter is 3
subLocal is 4
```

It is in question because -- while it's true that you've called endmacro from a sub, I believe this was just poorly programmed behavior to begin with.  In the context of how an :OnExit call is structured according to its original intent and documentation (as the last part of a Sub Main function) -- I believe that original behavior should be that variable expectations are as they are in Sub Main, to avoid confusion on having to know context of WHERE endmacro was called when you're programming your OnExit.

My expectation would be you would not see the subLocal and you would see the subOuter at that point in time.  Therefore the current behavior is also incorrect (though I appreciate you going for consistency).  It is somewhat of a breaking change, but if anyone was expecting the current behavior I posit that it's only by accident.  Programming to anticipate that would be a nightmare.

Example of expected output (which matches your original pr test):
```
mainOuter is 1
mainLocal is 2
subOuter is 3
```

And example of the test so that expectation is clear (based on your original test):
```
Sub Main()
    /echo \ay** Testing issue 703               **
	/echo \ay** Test 6: /endmac variable scope  **
	/echo \ayOutput should be:
	/echo \ao   Testing Issue703-6
    /echo \ao   testEnd1: /endmac
	/echo \ao   In :OnExit, calling Main Exit.
	/echo \ao   In MainExit
    /echo \ao   mainOuter is 1
    /echo \ao   mainLocal is 2
    /echo \ao   subOuter is 3
	/echo \ag========================
	/echo \ag====  BEGIN OUTPUT =====
	/echo \ag========================
    /echo Testing Issue703-6
	/declare mainOuter	int	outer 1
	/declare mainLocal	int local 2
	/call testEnd1
	/echo FAILURE!
:OnExit
	/echo In :OnExit, calling Main Exit.
	/call MainExit

	/if (${Defined[mainOuter]}) {
		/echo mainOuter is ${mainOuter}
	}
	/if (${Defined[mainLocal]}) {
		/echo mainLocal is ${mainLocal}
	}
	/if (${Defined[subOuter]}) {
		/echo subOuter is ${subOuter}
	}
	/if (${Defined[subLocal]}) {
		/echo subLocal is ${subLocal}
	}
	/endmac
/return

Sub testEnd1()
	/declare subOuter	int	outer 3
	/declare subLocal	int local 4
    /echo testEnd1: /endmac
	/endmac
	/echo FAILURE!
/return

Sub MainExit
    /echo In MainExit
/return
```
