### ISSUE TITLE
CDisplay::WriteTextHD2() function

### ISSUE THREAD

**Issue by evreqe** [macroquest/macroquest#732]
i think the EQ devs moved the CDisplay::WriteTextHD2() function out of the CDisplay class
so it would be a free standing function like DrawNetStatus()
not a big deal if you do not use this function since i think most stuff uses CTextureFont::DrawWrappedText() but i think this was making my game crash

version date of EQ "Jul 10 2023"
version time of EQ "09:40:10"

**Comment by brainiac** [comment]
Its a static function. its already free standing
