### ISSUE TITLE
Me.Silenced is showing NULL even when silenced

### ISSUE THREAD

**Issue by ofnature** [macroquest/macroquest#739]
**Describe the bug**
Me.Silenced is showing NULL even when silenced.

**To Reproduce**
on live go into the raid in firefall pass walk up to the boss mob and you will get silenced without triggering the raid.

**Expected behavior**
Me.Silenced should return the slot id of the debuff/buff if it on you.

**Screenshots**
![image](https://github.com/macroquest/macroquest/assets/65107780/3c564770-348d-4a2f-9fa5-f6182f7143e7)

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**
I believe it might be due to the fact that new raid buffs have multiple slots for spa and mq might not be reading past a certain slot count.

**Comment by ofnature** [comment]
here is the spell in question from the picture https://spells.eqresource.com/rawspells.php?id=52942

**Comment by Sicprofundus** [comment]
hrm, i can't edit it, but can you put "Me.Silenced is showing NULL even when silenced." or something similar in the title.

just putting [BUG] isn't really helpful

**Comment by pikipiki2** [comment]
This seems pretty much one issue we disacussed a bit oon Discord back inJanuary already [https://discord.com/channels/511690098136580097/511690098136580099/1067155574313201805](url)
