### ISSUE TITLE
Find the source of the familiar auto leave check box

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#741]
**Describe the bug**
checking the state of a checkbox no longer works if the checkbox isn't visible

per @brainiac "checked state only gets updated from PcClient on show", "i have on idea what it is, but it could be something like Profilemanager"

**To Reproduce**
try and detect and set a checkbox without it being visible
```
// EQ allows auto dismissal of familiars, but you have to turn it on.
// the auto dismiss option is in the KeyRingWnd under "KRW_Familiars_AutoLeaveButton"
#ifdef HAS_KEYRING_WINDOW
    if (CXWnd* keyringwnd = FindMQ2Window("KeyRingWnd")) {
        if (CButtonWnd* autoleavebtn = (CButtonWnd*)keyringwnd->GetChildItem("KRW_Familiars_AutoLeaveButton")) {
            if (!autoleavebtn->Checked) {
                SendWndClick2(autoleavebtn, "leftmouseup");
            }
        }
    }
#endif
```

**Expected behavior**
if this checkbox is unchecked, we would see it was unchecked and then check it

**Screenshots**

**MQ Version**
Live

**Comment by dannuic** [comment]
It doesn't sound like a general solution to this is available. Was brainiac talking about a work around for a specific checkbox?

**Comment by Sicprofundus** [comment]
He had some ideas, and said that I should put up a bug about it so it wouldn't get forgotten.

**Comment by brainiac** [comment]
dannuic is correct -- this conversation was very specific to the checkbox that was in question.

**Comment by Sicprofundus** [comment]
gotcha, now i understand

**Comment by brainiac** [comment]
This can be accessed now with
```c++
if (pLocalPC->IsFamiliarAutoLeaveEnabled()) {
    // ...
}
```
