### ISSUE TITLE
[BUG] cannot mq.delay during require showing up when it shouldn't

### ISSUE THREAD

**Issue by aquietone** [macroquest/macroquest#743]
**Describe the bug**
Similar to the PackageMan.Require issue which was worked around by checking for existence of the file instead of using require with pcall, it seems like any use of require in pcall where the require fails amounts to the same issue.

When looking into issue in LEM where binds get orphaned and can't be created upon script restart, found that LEM would error with the "cannot delay during require" if I tried to load an event which had any sort of lua error in it. LEM uses pcall to require the scripts for users events, and normally reports an error if those fail to load due to something like syntax issues.

I can work around this in a local build if I change https://github.com/macroquest/macroquest/blob/master/src/plugins/lua/bindings/lua_Globals.cpp#L61 to `sol::protected_function` in my local build, but then that results in basically every require being treated as if it were wrapped in `pcall`.

The ScopedYieldDisabler destructor is supposed to set the thread yield allowed back to true, but is that not happening immediately after the require or something?

**To Reproduce**
```lua
local mq = require('mq')
pcall(require, 'dne')
mq.delay(100)
```
where `dne` is some non-existent file. This will result in the cannot delay during require error.

**Expected behavior**
The script should not error due to the next mq.delay that it finds after the failed require.

**Screenshots**
```
Registering event: testXnames
Registering event: OMMmask
Event registration failed: testing123
d:\git\github\aquietone\mq\lua\lem\init.lua:980: Cannot delay while importing a module
stack traceback:
    [C]: in function 'delay'
    d:\git\github\aquietone\mq\lua\lem\init.lua:980: in main chunk
```

**MQ Version**
- [x] Live
- [x] Test
- [x] Emu (ROF2)

**Additional context**
[Discord discussion.](https://discord.com/channels/511690098136580097/866047684242309140/1134955678625189972)

**Comment by brainiac** [comment]
This was the same problem as #744. My fix should address both issues.
