### ISSUE TITLE
AbilityReady(abilityname) returns wrong boolean type

### ISSUE THREAD

**Issue by WilyeECoyote** [macroquest/macroquest#745]
**Describe the bug**
when running mq.TLO.Me.AbilityReady('Forage') in a print or other command it returns TRUE/FALSE in capital letters boolean type

**Expected behavior**
true/false in small letters boolean type

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Comment by brainiac** [comment]
You’re missing a () at the end

**Comment by brainiac** [comment]
Double checked. Its correct. Make sure you're evaluating the result, or you'll get the __tostring() result of the userdata instead of the actual datatype you want:

```
> print(mq.TLO.Me.AbilityReady('Forage'))
TRUE
```

```
print(mq.TLO.Me.AbilityReady('Forage')())
true
```
