### ISSUE TITLE
[BUG][LUA] AbilityReady(abilityname) returns wrong boolean type

### ISSUE THREAD

**Issue by WilyeECoyote** [macroquest/macroquest#746]
**Describe the bug**
when running mq.TLO.Me.AbilityReady('Forage') in a print or other command it returns TRUE/FALSE in capital letters boolean type

**Expected behavior**
true/false in small letters boolean type

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Comment by brainiac** [comment]
Duplicate of #745
