### ISSUE TITLE
[BUG]  *.Look TLO is broken

### ISSUE THREAD

**Issue by ew6082** [macroquest/macroquest#747]
**Describe the bug**
>.Look TLO returns 0.00 instead of the actual heading.

**To Reproduce**
/lua parse mq.TLO.Target.Look()
/lua parse mq.TLO.Me.Look()

**Expected behavior**
Return should be the angle spawn is facing

**Screenshots**

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**
My script is acting funny!

**Comment by brainiac** [comment]
Look is the up/down angle. Just confirmed that these values are correct.

More data may be necessary to understand your issue, but as currently written everything is working as expected.
