### ISSUE TITLE
lua TLO.Target.Snared always empty

### ISSUE THREAD

**Issue by wryates** [macroquest/macroquest#751]
**Describe the bug**
print(mq.TLO.Target.Snared) including buff counts when just having snare on the target.  

**To Reproduce**
Snare a mob with ranger low level Snare, it wont get populated

**Expected behavior**
Should return weather the mob is snared or not so we dont recast

**MQ Version**
- [ ] Live
- [ ] Test
- [X] Emu (ROF2)

**Comment by Sicprofundus** [comment]
Missing `()`

**Comment by brainiac** [comment]
I'm confused by this discription. "populated" doesn't mean anything to me, the return value is always populated.

This wouldn't be a lua issue, as the same behavior would be replicated with `/echo ${Target.Snared}`

**Comment by wryates** [comment]
When when running a test script, im printing out print(mq.TLO.Target.Snared()) returns nil and print(mq.TLO.Target.Snared) returns NULL, also when testing this i tried both the low level ranger snare and low level shadowknight darkness, and they hit, but the retuns is still nill or NULL even when the mob really is snared

**Comment by wryates** [comment]
I think i found the issue, it was a server setting turned off that sends the targets buffs back = Spells:AlwaysSendTargetsBuffs it seems to be working now
