### ISSUE TITLE
buff -> Caster bug (looks like an eq bug)

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#758]
This appears to be an EQ bug, so unless an eqbugfix can fix it, it isn't something for MQ - but i want it documented because it does break quite a few things.

the buff window is updating the "Caster" field of dots based on the last character to cast the dot on them

in this image there are two "Pyre of Va Xakra Rk. III" dots on the mob - if you inspect each image it shows the name of the last caster on both (yellow outline being what is supposed to be my dot, and red on not-mine).

![image](https://github.com/macroquest/macroquest/assets/48923666/42e3d1ea-175e-4d1e-90c3-c7a4f4079c3e)
![image](https://github.com/macroquest/macroquest/assets/48923666/02424f70-c1b4-4ac5-9efa-b9efd66bcf7c)

there was a bug like this a year or two ago but it appeared to have gone away - appears to be back.

You can replicate this by two of the same class (and can use guild hall dummy for testing).

steps:
- cast your dot on the dummy
- right click and inspect the yellow bordered dot
- observe it has your name

- using a second character of the same class with the same dot, cast the dot on the dummy
- right-click and inspect both the yellow bordered dot and the non-yellow bordered dot
- observe they both have the name of the second character

**Comment by brainiac** [comment]
This is the name that the server sends to the client, so if its wrong here its going to be wrong in MQ, too. Nothing that we can do about that.
