### ISSUE TITLE
Dear ImGui Demo Crash with Item Picker

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#764]
open Dear ImGuiDemo -> Tools -> Metrics/Debugger -> Tools

click "Item Picker"
then
click "Item Picker" a second time

crash

**Comment by brainiac** [comment]
So this is actually working as intended.

Its designed to put a breakpoint at the point where the item is being rendered. If you don't have a debugger attached, the dialog popup looks like a crash, but its actually a debug breakpoint.

You'd want to click ignore if you don't want to crash, retry if you want to attach a debugger and try again, and abort if you're silly and just want eq to go away.

**Comment by Sicprofundus** [comment]
right - for some reason i thought that was "right click to break", but yep, i misread
