### ISSUE TITLE
[BUG] mq.pickle does not handle double values correctly in nested tables

### ISSUE THREAD

**Issue by projecteon** [macroquest/macroquest#771]
**Describe the bug**
When pickle persists the table, the number is rounded to nearest int.

**To Reproduce**
```lua
local mq = require 'mq'
local double = 0.8
mq.pickle(string.format("%s/%s", mq.configDir, "double.lua"), {general= {scale = double}})
```

**Expected behavior**
Table is persisted with the correct double value

**Screenshots**
Table is persisted as
```lua
return {
    ['general'] = {
        ['scale'] = 1,
    },
}
```

**MQ Version**
- [x] Live
- [x] Test
- [x] Emu (ROF2)

**Additional Information**
This test indicates that it only happens for nested tables
```lua
local mq = require 'mq'
local double = 0.8
mq.pickle(string.format("%s/%s", mq.configDir, "double.lua"), {scale = double})

return {
    ['scale'] = 0.7999999999999999,
}
```

**Comment by brainiac** [comment]
fixed by 416b4f89ecf07398056cfe1590d2dbed9395a4e7
