### ISSUE TITLE
[BUG] /removelev failing and sometimes crashing on Test

### ISSUE THREAD

**Issue by hytiek** [macroquest/macroquest#779]
On TEST using latest build as of 11/11/2023 from RedGuides the `/removelev` command was not successfully stripping the levitation buff even though it referenced the "Removing buff: <name of lev buff>"

1. Update to latest build for Test
2. Load up a toon which can cast a levitation spell on self
3. Cast the levitation spell (or aa) on self
4. Confirm that the buff is in the buff list
5. Use: /removelev
6. If you don't crash, notice that it shows that it wants to remove the correct buff, but doesn't. 

Expectation is that running /removelev would strip the levitation buff.

**MQ Version**
- [ ] Live
- [ X ] Test
- [ ] Emu (ROF2)

Reporting on behalf of RG user and confirmed via another Test player.

I'm not on latest build for Live so I did not check that the problem exists on Live.

**Comment by Knightly1** [comment]
Just to be clear when you say "it shows it wants to remove the correct buff" what you mean is it outputs `Removing: Levitate` or whatever, yes?

**Comment by hytiek** [comment]
Yes that's correct.

**Comment by hytiek** [comment]
Live RG was just tested with latest patch and the `/removelev` works as expected.

**Comment by brainiac** [comment]
should be fixed now
