### ISSUE TITLE
[BUG] NamedPipe failing on linux/wine

### ISSUE THREAD

**Issue by HK47196** [macroquest/macroquest#780]
**Describe the bug**
MQ spams errors when used on wine due to the namedpipe/postoffice failing to connect. I do _not_ think this is an issue with WINE, but an unhandled error that simply isn't observed on Windows(?). Specifically, the error is ERROR_MORE_DATA. 

**To Reproduce**
1. Use latest MQ on wine/linux. Will see unending error spam, high CPU usage, etc.,

**Expected behavior**
Expected to run fine.

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**
I admittedly don't know much of anything about the Windows API. After reading the documentation and looking at examples, I patched it like so and it works fine:

```diff
diff --git a/src/common/NamedPipes.cpp b/src/common/NamedPipes.cpp
index fcffa0fe..aa697018 100644
--- a/src/common/NamedPipes.cpp
+++ b/src/common/NamedPipes.cpp
@@ -267,9 +267,12 @@ void PipeConnection::InternalBeginRead()
 
 	if (!readStarted)
 	{
-		SPDLOG_ERROR("{} connectionId={}",
-			fmt::windows_error(GetLastError(), "Failed at ::ReadFileEx").what(), m_connectionId);
-		m_parent->CloseConnection(this);
+		auto error = GetLastError();
+		if(error != ERROR_MORE_DATA) {
+			SPDLOG_ERROR("{} connectionId={}",
+				fmt::windows_error(error, "Failed at ::ReadFileEx").what(), m_connectionId);
+			m_parent->CloseConnection(this);
+		}
 	}
 }
 
@@ -331,11 +334,12 @@ void PipeConnection::HandleReadComplete(uint32_t errorCode, uint32_t bytesRead)
 
 	case ERROR_INSUFFICIENT_BUFFER:
 	case ERROR_SUCCESS:
+	case ERROR_MORE_DATA:
 		// Store the data in our buffers, and try to read more. If we've got all the
 		// data we need we can process it right after the next call to ReadFileEx.
 		m_readBuffers.emplace_back(std::move(m_readBuffer), bytesRead);
 
-		if (!moreData)
+		if (!moreData && errorCode != ERROR_MORE_DATA)
 		{
 			ProcessBuffers();
 		}
```

I'm not submitting a PR because I don't know if this is actually right. This is based on the documentation for _ReadFile_ rather than _ReadFileEx_:
https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile
>If a named pipe is being read in message mode and the next message is longer than the nNumberOfBytesToRead parameter specifies, ReadFile returns FALSE and GetLastError returns ERROR_MORE_DATA. The remainder of the message can be read by a subsequent call to the ReadFile or PeekNamedPipe function.

ReadFileEx's documentation is silent on this.

**Comment by dannuic** [comment]
I don't actually see an issue with this solution -- but @brainiac might know more since he implemented the actual pipe internals

**Comment by brainiac** [comment]
I can't really tell from a diff, would be better as a pull request. logically it seems fine but i'm not sure if there is anything else that would need to change.
