### ISSUE TITLE
[BUG] Trader window inventory slots override itemslot / itemslot2 of items in bags

### ISSUE THREAD

**Issue by aquietone** [macroquest/macroquest#781]
**Describe the bug**
Derple found that opening the /trader window changes the ItemSlot values of items inside of trader satchels.

ItemSlot and ItemSlot2 return the index in the trader window (0, 1, ...) and -1 when the trader window is open for any items which are in trader satchels. This means you can't get the position of the items in the trader satchels with FindItem and have to iterate over inventory slots.

**To Reproduce**
1. Buy a trader satchel and put an item into the trader satchel
2. Get the ItemSlot and ItemSlot2 of the item in the trader satchel, for example 32, 1.
3. Open the trader window /trader
4. Get the ItemSlot and ItemSlot2 of the same item in the trader satchel, and the values are now 0, -1
5. Close the /trader window and ItemSlot and ItemSlot2 are still 0, -1
6. Pick up and put down the item in the same spot and observe the correct values again of 32, 1.

**Expected behavior**
This seems like its just how EQ works. Would have thought FindItem would still give the slot numbers of the bag, not of the trader window.

**Screenshots**
From Brainiac:
![image](https://github.com/macroquest/macroquest/assets/100880604/0036b982-a67b-432c-93f8-a34f1d571e62)
```
so EQ is modifying the ItemGlobalIndex of items that are inside the satchel
so the satchel is 
GlobalIndex    {Location=eItemContainerPossessions (0) Index=[26, -1, -1] }    eqlib::ItemGlobalIndex
but the items inside it are
GlobalIndex    {Location=eItemContainerBazaar (12) Index=[0, -1, -1] }    eqlib::ItemGlobalIndex
```

**MQ Version**
- [x] Live
- [x] Test
- [x] Emu (ROF2)

**Additional context**
https://discord.com/channels/511690098136580097/866047684242309140/1173507740790956092

**Comment by brainiac** [comment]
Spent some time thinking aobut this. I don't think we can fix this as its EQ manipulating its own data by changing the location of its items.
