### ISSUE TITLE
[BUG] No Spell info in EQUI_SpellDisplay.xml

### ISSUE THREAD

**Issue by LamahHerder** [macroquest/macroquest#782]
**Describe the bug**
Spell info only shows in EQUI_ItemDisplay.xml and not in EQUI_SpellDisplay.xml

**To Reproduce**

1. Right click a buff or spell gem to popup spelldisplay
2. Notice no MQ info
3. Right click an item with a spell on it 
4. Notice MQ info for the spell

**Expected behavior**
Spell info is shown in spell popups

**MQ Version**
- [x] Live / TLP

**Additional context**
![image](https://github.com/macroquest/macroquest/assets/22425296/84f297bb-525a-49b1-a637-c3691c17ab58)

**Comment by bytebite01** [comment]
I managed to attach to a debugger and see the SpellID is loading in Wrong at MQ2ItemDisplay.cpp:1656.  

If it works it is a collision.  Currently getting 29281 for druid spell which is a shaman disease.

**Comment by truculent1** [comment]
Getting the exact same issue.
Mine currently only pulls 29285 and 7998. Hope that's relevant.
