### ISSUE TITLE
[BUG] Target.Buff[spell].ID not showing when it is < 10ish seconds

### ISSUE THREAD

**Issue by fluffster** [macroquest/macroquest#787]
If you ${Target.Buff[Spell Name].ID} it will show the spell ID.. However when the spell gets down in time (Like a DOT) and gets to like 10ish seconds it will show NULL even when the spell is still on them and ticking down. This goes for any dot like spell. I have not checked other spells.  This applies to Duration as well. Seems like on that the buff timer slips during the count down. It starts and matches up with the timer in the Target window. However as it counts down the timer splits away from the Target Window.

Boastful Bellow
Pyre of Va Xakraj

And so on.

** To reproduce **
Just cast a dot (Example Boastful Bellow from bard)
/echo ${Target.Buff[Boastful Bellow].ID} ${Target.Buff[Boastful Bellow].Duration}

Just watch the Target window for the spell there and the timer. Then match that timer with output of the echo. You will notice the duration starts to drift from the Target window. And about 10 seconds it actually says NULL for both ID and Duration even though the Target window still shows the spell and timer on it.

**Expected behavior**
I would expect Target.Buff[spellname].ID to show as long as the buff is still on them. Same for Duration. 

**Screenshots**
Cant really show it. But easily reproducable.

**MQ Version**
- [ * ] Live
- [ ] Test
- [ ] Emu (ROF2)

**Comment by dannuic** [comment]
This is a well-known EQ bug -- the client timing and server timing differ. You can see it without MQ, and there's nothing we can really do about it.
