### ISSUE TITLE
[BUG] Spawns showing garbage "deleted" or random characters + crash

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#798]
sometimes mq2map is displaying garbage characters for spawns
![image](https://github.com/macroquest/macroquest/assets/48923666/b6363477-7aa4-4f99-9fc6-dd5be85f0824)

![image](https://github.com/macroquest/macroquest/assets/48923666/757e189c-7bb6-4d93-9bcd-2b0593836d78)

![image](https://github.com/macroquest/macroquest/assets/48923666/26a12d9e-f716-42d5-aafd-4782fd00c34b)

sometimes the map will be populated with "deleted"

![image](https://github.com/macroquest/macroquest/assets/48923666/dd64b61c-6d43-444f-8f53-0a4d28762fe9)

Possibly related to this crash that @jessebevil caught
![image](https://github.com/macroquest/macroquest/assets/48923666/e3551078-6a4f-4242-877b-9f5dc251e8d0)

![image](https://github.com/macroquest/macroquest/assets/48923666/e347dde6-ec04-4ed3-8d28-9b9546db33bd)

chat's work around code - was able to keep crashing moving in and out of the guild hall's regeneration pool

```cpp
int GetBodyType(SPAWNINFO* pSpawn)
{
    if (pSpawn != nullptr && pSpawn->BodyType != nullptr)
    {
        if (!_stricmp(pSpawn->Name, "deleted")) {
            WriteChatf("Avoided a crash in GetBodyType because name was \"Deleted\"");
            return 0;
        }

        for (int i = 0; i < CharacterProperty_Last; i++)
        {
            if (pSpawn->HasProperty(i))
            {
                if (i == CharacterProperty_Utility)
                {
                    if (pSpawn->HasProperty(i, CharacterProperty_Trap))
                        return CharacterProperty_Trap;
                    if (pSpawn->HasProperty(i, CharacterProperty_Companion))
                        return CharacterProperty_Companion;
                    if (pSpawn->HasProperty(i, CharacterProperty_Suicide))
                        return CharacterProperty_Suicide;
                }
                return i;
            }
        }
    }

    return 0;
}
```
![image](https://github.com/macroquest/macroquest/assets/48923666/069e7182-c85f-4129-a575-dd4f2845fa36)

**Comment by Sicprofundus** [comment]
this one was shared with me today - the map filter "trigger" appears to be what it is
if you have garbage, then toggle off "trigger, then toggle back on, there is no garbage
![image](https://github.com/macroquest/macroquest/assets/48923666/65d491ae-27d2-4b82-bf10-19cd828e19af)

**Comment by brainiac** [comment]
I haven't seen any related crashes with this fix yet. Marking this as fixed. If we see this still occur on the latest code we'll revisit.
