### ISSUE TITLE
Zone for Task Objectives

### ISSUE THREAD

**Issue by joligario** [macroquest/macroquest#800]
https://github.com/macroquest/macroquest/blob/15d8e89aac1da844f1bc99e461facd4e7e926278/src/main/datatypes/MQ2TaskType.cpp#L636

Should be ZoneID instead of TargetZoneID. When testing task `Basic Training` in tutorialb, ZoneID gives 189 while TargetZoneID gave me 1547.

**Comment by brainiac** [comment]
For reference, it looks like TargetZoneID is the instance based zone tied to the objective, and ZoneID is the base zone.

**Comment by joligario** [comment]
Yeah, that's what I figured. Thanks!
