### ISSUE TITLE
[BUG] Images no longer display with CreateMethod like in examples/texture.lua

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#802]
**MQ Version**

- [X ] Test

Images no longer appear to be loading utilizing the method in

https://github.com/macroquest/macroquest/blob/master/src/plugins/lua/lua/examples/texture.lua

**To Reproduce**
1. /lua run texture
2. Click on Load

This is what displays on Test
![image](https://github.com/macroquest/macroquest/assets/48923666/a196c7f8-4e68-43cc-94d0-0902a099d9c7)

**Expected behavior**
Expect the image to load
this is what it looks like on Live
![image](https://github.com/macroquest/macroquest/assets/48923666/737b8a61-543e-405a-b6e6-d640b5bdea55)

**MQ Version**

- [X ] Test

**Comment by brainiac** [comment]
fixed a couple days ago
