### ISSUE TITLE
[BUG] ${Me.Origin} only seems to return either NULL or South Qeynos

### ISSUE THREAD

**Issue by knave23** [macroquest/macroquest#807]
**Describe the bug**
Noticed when trying to run adventurerstone.mac, but also if you just /echo ${Me.Origin} it returns incorrectly. It seems like f2p's get NULL and gold toons get "South Qeynos" but that isn't always correct, e.g. my Dark Elf who's starting city is Neriak gets South Qeynos returned. It definitely has worked on f2p's because I've run the adventurer stone macro on them before.

Edit to add: tested a smidge more and just wanted to clarify it doesn't seem tied to active subs; a "gold" toon that has a non-Crescent Reach starting city but isn't actively subbed returned South Qeynos too, while an originally f2p toon that got krono'd once but it's also lapsed returned NULL.

**To Reproduce**
1. /echo ${Me.Origin}

**Expected behavior**
Output the character's correct starting city

**Screenshots**

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**

**Comment by brainiac** [comment]
Fixed

**Comment by knave23** [comment]
Thanks! Is there a pull request I can look at just for my own edification? I looked at the list, but none jumped out at me as for this ticket.

**Comment by brainiac** [comment]
It was fixed in eqlib. The starting location value had been swapped with another
