### ISSUE TITLE
Mercenary.State incorrectly showing ACTIVE as UNKNOWN post 1/17/24

### ISSUE THREAD

**Issue by Sicprofundus** [macroquest/macroquest#811]
per playj at RG
https://www.redguides.com/community/threads/mercenary-state-incorrectly-showing-active-as-unknown-post-1-17-24.89729/

Post patch (1/17) seems like something changed in Mercenary.State

INI:
/echo ${Mercenary.State}
shows UNKNOWN even though merc should be ACTIVE (it is also in balanced stance)

Tried zoning, no improvement. This is across multiple chars and multiple computers.

SUSPENDED correctly shows SUSPENDED

**Comment by bytebite01** [comment]
StateID is now 6 for active it looks like.  Active was 5.  Temp workaround is using StateID and own interpretation of values.
