### ISSUE TITLE
[BUG] Heading TLO outputs Name and ShortName backwards.

### ISSUE THREAD

**Issue by XeniazMmobugs** [macroquest/macroquest#813]
**Describe the bug**
${Heading[15].Name} and ${Heading[15].ShortName} are swapped when feeding it the BoundLocation heading.
In this case, the Heading value is 483.00

**To Reproduce**
```/echo I am bound in ${Me.BoundLocation[0].Zone.Name} at X: ${Me.BoundLocation[0].X} Y: ${Me.BoundLocation[0].Y} Z: ${Me.BoundLocation[0].Z} facing ${Heading[${Me.BoundLocation[0].Heading}].ShortName}```

I am bound in Guild Lobby at X: -28.00 Y: 561.00 Z: 2.00 facing west

```/echo I am bound in ${Me.BoundLocation[0].Zone.Name} at X: ${Me.BoundLocation[0].X} Y: ${Me.BoundLocation[0].Y} Z: ${Me.BoundLocation[0].Z} facing ${Heading[${Me.BoundLocation[0].Heading}].Name}```

I am bound in Guild Lobby at X: -28.00 Y: 561.00 Z: 2.00 facing W

**MQ Version**
- [ ] Live

**Additional context**
Would also suggest making Me.BoundLocation[0].Heading return a Heading type instead of a float.

**Comment by brainiac** [comment]
I'm not seeing this reproduce. I am getting the correct results

```
> /echo I am bound in ${Me.BoundLocation[0].Zone.Name} at X: ${Me.BoundLocation[0].X} Y: ${Me.BoundLocation[0].Y} Z: ${Me.BoundLocation[0].Z} facing ${Heading[${Me.BoundLocation[0].Heading}].ShortName}
I am bound in The Plane of Knowledge at X: -59.03 Y: -218.26 Z: -157.24 facing SSW
> /echo I am bound in ${Me.BoundLocation[0].Zone.Name} at X: ${Me.BoundLocation[0].X} Y: ${Me.BoundLocation[0].Y} Z: ${Me.BoundLocation[0].Z} facing ${Heading[${Me.BoundLocation[0].Heading}].Name}
I am bound in The Plane of Knowledge at X: -59.03 Y: -218.26 Z: -157.24 facing south by southwest
```

**Comment by brainiac** [comment]
Hmm... Specifically the issue is with "west" and not anything to do with bound location.

oh its a damn buffer underflow. Its actually indexing a negative value. Thats a bug, I'll fix.

**Comment by brainiac** [comment]
ZoneBoundHeading isn't even in degrees, so you can't even use it with Heading

**Comment by brainiac** [comment]
it now also returns a Heading
