### ISSUE TITLE
[BUG] client crash if nil value passed into mq.parse(value)

### ISSUE THREAD

**Issue by aquietone** [macroquest/macroquest#821]
**Describe the bug**
If you accidentally pass in a nil value to `mq.parse(value)`, the client closes with no crash popup or anything. At least, no popup on emu. Maybe its more informative on live.

**To Reproduce**
`/lua parse mq.parse(nil)`

**Expected behavior**
Not to crash

**MQ Version**
- [ ] Live
- [ ] Test
- [x] Emu (ROF2)

**Comment by brainiac** [comment]
on emu yeah, luajit exception handling is virtually non-existence on emu. There is very little I can do.

**Comment by aquietone** [comment]
confirmed it causes the eq client to just close the same way on live. just a missing null check on the input to the mq.parse method probably?

**Comment by brainiac** [comment]
Well that is certainly unexpected. it gives me an error in debug.

**Comment by brainiac** [comment]
```
> /lua parse mq.parse(nil)
bad argument #1 to '?' (Expected string, got nil)
stack traceback:
	[C]: in ?
---- Begin Stack (size: 1) ----
1 -- (-1) ---- nil
---- End Stack ----
```
