### ISSUE TITLE
[BUG] Test Server: ${Me.Cash} or ${Me.Platinum} only returns 0

### ISSUE THREAD

**Issue by Werkfakter** [macroquest/macroquest#829]
**Describe the bug**
Following the recent update to the test build on 2/14/2024, I can't get the amount of money to return as anything but 0.

**To Reproduce**
This is using:

${Me.Cash}
${Me.Platinum}
${Me.Gold}
${Me.CashBank}
etc...

**Expected behavior**
The amount of money on character or bank should return as an int

**Screenshots**
None

**MQ Version**
- [ ] Live
- [X] Test
- [ ] Emu (ROF2)

**Additional context**
Tested on Live and confirmed that calls for money return correctly

**Comment by brainiac** [comment]
Fixed this earlier this evening with 4e01db2ea3b181171f33ae44c111f4b25bd1dfbc
