### ISSUE TITLE
[BUG] New Instance Closes RG Menu

### ISSUE THREAD

**Issue by knave23** [macroquest/macroquest#835]
**Describe the bug**
I don't _think_ this used to happen, but if it did then I guess this is a QoL request? When I Rclick RG in the system tray and launch an instance, if I then RClick again, like to launch another character, the menu gets closed when the first instance opens up. This might be a windows thing, but since I'm pretty sure it only started with the latest update I figured I'd mention it. 

**To Reproduce**
1. Launch a couple characters from autologin via the "launch all checked" option
2. Before the EQ instances start up, open the menu again as if to launch another autologin character but don't yet
3. Note that when the previous instance launches, the menu gets closed

**Expected behavior**
Menu should stay open

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Comment by brainiac** [comment]
This is because EQ is rude and steals focus. Menus close automatically when focus is lost.

**Comment by knave23** [comment]
Ah ok. I assumed, but since I thought it was a new behavior I'd ask. Thanks!
