### ISSUE TITLE
${Me.Origin} Returns Null on Emu

### ISSUE THREAD

**Issue by Venoryk** [macroquest/macroquest#836]
When attempting to run adventurerstone.mac it calls ${Me.Origin} which returns null on Project Lazarus 

**To Reproduce**

/echo ${Me.Origin}

**Expected behavior**
Output characters starting city

**Comment by brainiac** [comment]
the EQEmu server does not currently send this information down. MQ is reporting this value correctly, it is just blank.

There is nothing MQ can do without this information, so the server would need to fix this.
