### ISSUE TITLE
AutoLogin doesn't handle the character load delay message

### ISSUE THREAD

**Issue by Knightly1** [macroquest/macroquest#839]
**Describe the bug**
Autologin doesn't handle the popup for "It took X seconds to load your characters"  More context here: https://discord.com/channels/511690098136580097/678065336821612546/1210676225744314399

**To Reproduce**
1. Start logging in with autologin
2. After server select, cause a brief internet connection interruption
3. Get the message about character load delay
4. Note that autologin waits at this point until you click ok

**Expected behavior**
Autologin should handle the popup and click it for you (possibly writing to chat that it did so since this is a "Please contact someone if something is missing" thing)

**Screenshots**
![image](https://github.com/macroquest/macroquest/assets/55611098/397ce23c-6d9c-472a-8b03-3ddab0b7dd02)

**MQ Version**
- [X] Live
- [X] Test
- [ ] Emu (ROF2)

**Comment by brainiac** [comment]
Adding a few more

![image](https://github.com/macroquest/macroquest/assets/57729/6de90522-4c5f-4a45-bc9a-c1ef63fa3754)
![image](https://github.com/macroquest/macroquest/assets/57729/5a231d46-f380-4d59-b4cd-7e6ec57d0d0c)
![image](https://github.com/macroquest/macroquest/assets/57729/5c2fbb44-943f-43ab-aec2-66e819e7e7a8)
![image](https://github.com/macroquest/macroquest/assets/57729/11d4a38f-267d-4bd4-be32-861cc2c857ee)

**Comment by brainiac** [comment]
I'm not going to bother with those for now, i'll leave comments in the code about them. I think the only one worth worrying aobut is the "Your login cannot be validated"
