### ISSUE TITLE
Lua Task Manager - Launch Script...

### ISSUE THREAD

**Issue by Zoh63392187** [macroquest/macroquest#841]
Some times when I hit the button "Launch Script.." in the Lua task manager it makes EQ crash to desktop with no errors.
This just started resently with the last few builds and I'm using the plain build from this repo.

**Comment by Knightly1** [comment]
Is this a specific script or any/all scripts?

**Comment by Zoh63392187** [comment]
It when I want to select a Lua file and hit the button "Launch Script.." So I do not even get the chance to select anything
![image](https://github.com/macroquest/macroquest/assets/32987300/30d74704-0f0d-45c6-bd8b-18c6003bec18)

**Comment by Zoh63392187** [comment]
I no longer see this error and have no idea what was the cause. I will close for now as it really does not have much to go on.
