### ISSUE TITLE
[BUG] mq.TLO.Window('name')() returns string

### ISSUE THREAD

**Issue by yb-f** [macroquest/macroquest#845]
**Describe the bug**
in lua mq.TLO.Window('Name')() will return a string with TRUE or FALSE rather than an actual boolean of the window state.
using mq.TLO.Window('Name').Open() will properly return the boolean.

**To Reproduce**
Check value via lua of mq.TLO.WIndow('Name')()

**Expected behavior**
Should return a boolean not string

**Screenshots**

**MQ Version**
- [x] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**

**Comment by aquietone** [comment]
Calling it that way is just doing a tostring on the window object. You can add .Open() to get a Boolean.

**Comment by brainiac** [comment]
working as designed.
