### ISSUE TITLE
[BUG] ImGui keypress detector bindings do not work

### ISSUE THREAD

**Issue by DerpleMQ2** [macroquest/macroquest#848]
**Describe the bug**
ImGui does not correctly report keystate - specifically when chorded.

**To Reproduce**
1. Open the ImGui Demo
2. Look at the keystate section
3. Hit ctrl/alt/shit and other keys at the same time
4. Notice that the modifier keystate often gets stuck ON or does not register as being held down
5. things like Shift+1 or CTRL+ALT+1 become impossible to detect by lua scripts

**Expected behavior**
The keystate should be correct to the keyboard.

**MQ Version**
- [x] Live
- [x] Test
- [x] Emu (ROF2)

**Comment by LamahHerder** [comment]
subscribed... have need for keybind functionality in imgui

**Comment by grimmier378** [comment]
i am able to use mod key in alert master.

```
if ImGui.IsKeyDown(ImGuiMod.Ctrl) and ImGui.IsMouseReleased(1) then
      mq.cmdf('/noparse /dgza /docommand /timed ${Math.Rand[5,30]} /nav wp "%s"', desc)
  elseif ImGui.IsMouseReleased(1) then
     mq.cmdf('/nav wp "%s"', desc)
end
```

VSCode will throw a squiggle but this functions perfectly. ctrl right click nav group, else right click nav self

**Comment by brainiac** [comment]
Just spent the last hour or so looking into this in detail. Best that I can tell, this is working as expected.

IsKeyDown = is the key in the down state
IsKeyPressed = was this key pressed this frame.

If you're looking for key chords, you can't use IsKeyPressed.

**Comment by DerpleMQ2** [comment]
I am not sure how you tested this but I will send a video. IsKeyDown shows CTRL/Alt down even when they are let go. which is the problem.

**Comment by DerpleMQ2** [comment]
PMed you a video in discord

**Comment by DerpleMQ2** [comment]
> i am able to use mod key in alert master.
> 
> ```
> if ImGui.IsKeyDown(ImGuiMod.Ctrl) and ImGui.IsMouseReleased(1) then
>       mq.cmdf('/noparse /dgza /docommand /timed ${Math.Rand[5,30]} /nav wp "%s"', desc)
>   elseif ImGui.IsMouseReleased(1) then
>      mq.cmdf('/nav wp "%s"', desc)
> end
> ```
> 
> VSCode will throw a squiggle but this functions perfectly. ctrl right click nav group, else right click nav self

Mouse seems to work it is things like CTRL/ALT that get stuck in an ON-STATE you can even see this with Autologin where CTRL + click on a profile character marks it with a *, if you use ctrl+alt+# to swap game windows it gets stuck on the second client and will mark as * without holding ctrl.
