### ISSUE TITLE
[BUG] EMU /timestamp command changed from local to UTC

### ISSUE THREAD

**Issue by aquietone** [macroquest/macroquest#852]
**Describe the bug**
Previously, the timestamp chat command for emu used local timestamps. At some point, it changed to UTC.

**To Reproduce**
Turn on timestamps on an emu server.

**Expected behavior**
Timestamps should be in local time, the chat window isn't a log file.

**Screenshots**
![image](https://github.com/macroquest/macroquest/assets/100880604/0159ca43-f31f-4365-902a-ac5b40a7f752)

**MQ Version**
- [x] Emu (ROF2)

**Comment by aquietone** [comment]
existing:
```c++
std::string timeStampedMsg = fmt::format("[{:%H:%M:%S}] {}", std::chrono::time_point_cast<std::chrono::seconds>(std::chrono::system_clock::now()), szMsg);
```

a couple possible changes to print local time:
```c++
auto now = std::chrono::system_clock::now();
auto in_time_t = std::chrono::system_clock::to_time_t(now);
std::string timeStampedMsg = fmt::format("[{}] {}", std::put_time(std::localtime(&in_time_t), "%H:%M:%S"), szMsg);
```

```c++
std::time_t tt = std::time(nullptr);
std::tm* tm = std::localtime(&tt);
std::string timeStampedMsg = fmt::format("[{:%H:%M:%S}] {}", *tm, szMsg);
```

Idk if one of these is better than the other, or if there is some better way. Both work, although it complains about localtime and suggests localtime_s but then it doesn't recognize localtime_s.

**Comment by brainiac** [comment]
I have this solved, i'm working on some other logging-adjacent fixes before i push up the fixes
