### ISSUE TITLE
[BUG] /removeaura issue

### ISSUE THREAD

**Issue by Aipoc76** [macroquest/macroquest#869]
**Describe the bug**
Using the command /remove aura does not work when you list the aura as a variable.

When you type /removeaura SOMEAURA NAME  the command works as intended.
When you type /removeaura SOME AURA PARTIAL NAME the command works as intended.
When you type /removeaura ${AuraNameVariable} the command does nothing.
Even using ${Me.Aura[1].Name} does nothing.

**To Reproduce**
1. open console
2. use command /removeaura Some aura
3. start a macro
4. declare a aura variable and set it to your aura name
5. use command /removeaura ${VariableYouMade}
6. See that nothing happens.

**Expected behavior**
I expect the aura to be removed when using a variable that has been properly named and the aura is cast.

**Screenshots**
Using Variable
![image](https://github.com/macroquest/macroquest/assets/42475106/d26edafc-0e50-4868-b3ae-bb370fca5b0c)

now Manually removing
![image](https://github.com/macroquest/macroquest/assets/42475106/ead4f15e-3856-4422-8035-f37d28068aca)

Example of ${Me.Aura[1].Name}
![image](https://github.com/macroquest/macroquest/assets/42475106/bd9525b5-e728-4bb8-8c11-8709babb2c38)

**MQ Version**
- [X ] Live
- [ ] Test
- [ ] Emu (ROF2)

**Additional context**
I originally had a edit thinking it was just a specific spell.  Its not working with other auras either.

**Comment by brainiac** [comment]
note: RemoveAura doesn't have the parse flag, so it doesn't parse macro syntax

**Comment by brainiac** [comment]
Its always been this way

**Comment by Aipoc76** [comment]
weird, I guess I wrote and tested code that worked somehow when it shouldn't have.  Wouldn't be the first time I wrote something that worked when it shouldn't  :)
