### ISSUE TITLE
[BUG] Unusually High CPU Usage

### ISSUE THREAD

**Issue by knave23** [macroquest/macroquest#873]
**Describe the bug**
Seeing weirdly high CPU usage even when just idling with ~~RG launcher~~ MQ loader in systray and no eq instances. Seems to have started with the last patch. Didn't know if you all watched this thread, but some others have commented here: https://www.redguides.com/community/threads/very-vanilla-mq-live-servers.77019/post-619493

**To Reproduce**
1. Run latest MQ from RG Launcher
2. Check Task Manager and see 5-10% CPU usage from MQ App

**Expected behavior**
Minimal usage, especially while idling

**Screenshots**

**MQ Version**
- [x] Live
- [don't know, but presumably] Test
- [don't know, but presumably] Emu (ROF2)

**Additional context**

**Comment by Sicprofundus** [comment]
"just idling with RG Launcher in systray" - i think you mean the MQ loader

**Comment by knave23** [comment]
oh, yep! good catch sorry. Yes, the loader after having started MQ from the RG launcher

**Comment by Synk56** [comment]
also seeing this issue, when compiling older version of mq2 this goes away completely, seems imgui related

**Comment by brainiac** [comment]
it is the named pipe processing spinning instead of waiting for new messages to process.
