### ISSUE TITLE
AutoLogin, Alpha sort Charracters\ServerName list

### ISSUE THREAD

**Issue by LamahHerder** [macroquest/macroquest#887]
1. Right click MQ tray icon
2. Mouse over AutoLogin\Characters
3. Mouse Over AutoLogin\Characters\ServerName
4. This list of characters would be sorted alphabetically

**Comment by brainiac** [comment]
left click macroquest icon -> autologin -> characters -> sort by whatever you want to sort.

**Comment by LamahHerder** [comment]
The sorting when you open full UI with left click does not transfer to the right click popouts

**Comment by brainiac** [comment]
> The sorting when you open full UI with left click does not transfer to the right click popouts

Yes it does. I double checked to confirm this behavior before I updated the ticket.
