### ISSUE TITLE
${NetBots[toonname].Buff[SpellName]} always returns first buff

### ISSUE THREAD

**Issue by nytemyst** [macroquest/macroquest#911]
**Describe the bug**
${NetBots[Name].Buff[spellname]} should return a spell type if the toon you're checking has the buff. It always returns the first buff seen no matter what is being supplied.

**To Reproduce**
1. do /echo ${NetBots[toonname].Buff[ferfefwrfee]} 

**Expected behavior**
I was expecting to see a spell returned if the toon has that debuff and null if not.

**Screenshots**

**MQ Version**
Live
**Additional context**

**Comment by brainiac** [comment]
We don't maintain netbots here. This needs to be reported to whatever repository owns NetBots.
